site_name: Thomsun's KB
site_url: https://thomsun.github.io/kb/

plugins:
    - search
    - awesome-pages
    - git-revision-date-localized:
        type: iso_datetime
        locale: en_US
        timezone: America/Los_Angeles
        enable_creation_date: true
        exclude:
            - index.md
            - about.md

theme:
    name: material
    custom_dir: custom_theme
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - content.code.annotate
        - toc.integrate


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

nav:
    - Home: index.md
    - ...
    - About: about.md
