site_name: Thomsun's KB
site_url: https://thomsun.github.io/kb/

theme:
    name: material
    features:
        - content.code.annotate

plugins:
    - search
    - git-revision-date-localized:
        type: iso_datetime
        locale: en_US
        timezone: America/Los_Angeles
        enable_creation_date: true

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

nav:
    - Home: index.md
    - About: about.md
