site_name: Thomsun's KB
site_url: https://thomsun.github.io/kb/

theme:
    name: material

plugins:
    - search
    - git-revision-date-localized:
        type: iso_datetime
        locale: en_US
        timezone: America/Los_Angeles
        enable_creation_date: true
nav:
    - Home: index.md
    - About: about.md
